---
# Address the service will listen on
glove_address: 0.0.0.0:8080

# How to store information (in memory or in the DynamoDB)
glove_db: dynamodb

# DB Table name
glove_db_table: glove

# URL to a substrate node endpoint
glove_node_endpoint: "wss://rpc-kusama.luckyfriday.io/"

# Secret phrase for the Glove proxy account.
# See https://wiki.polkadot.network/docs/learn-account-advanced#derivation-paths for more details.
glove_proxy_secret_phrase: "\"caution juice atom organ advance problem want pledge someone senior holiday very/0\""
